image: alpine/edge
sources:
- https://git.sr.ht/~rkta/microtojson
packages:
  - cppcheck
triggers:
  - action: email
    condition: failure
    to: mail@rkta.de
tasks:
- tests: |
    cd microtojson
    export CFLAGS=-Werror
    export DEVELOPER=1
    make ASAN=
- example: |
    cd microtojson
    export CFLAGS=-Werror
    export DEVELOPER=1
    make ASAN= example
- cppcheck: |
    cd microtojson
    make cppcheck
