image: openbsd/latest
sources:
- https://git.sr.ht/~rkta/microtojson
packages:
  - cppcheck
  - gmake
triggers:
  - action: email
    condition: failure
    to: mail@rkta.de
tasks:
- tests: |
    cd microtojson
    export CFLAGS='-Werror -Wno-missing-field-initializers'
    export DEVELOPER=1
    gmake ASAN= WSTACK= GCCFLAGS=
- example: |
    cd microtojson
    export CFLAGS='-Werror -Wno-missing-field-initializers'
    export DEVELOPER=1
    gmake ASAN= WSTACK= GCCFLAGS= example
- cppcheck: |
    cd microtojson
    gmake cppcheck
