image: openbsd/latest
sources:
- https://git.sr.ht/~rkta/microtojson
packages:
  - gmake
triggers:
  - action: email
    condition: failure
    to: mail@rkta.de
tasks:
- tests: |
    cd microtojson
    CFLAGS='-Werror -Wno-missing-field-initializers' gmake CC=cc ASAN= WSTACK= GCCFLAGS=
- example: |
    cd microtojson
    CFLAGS='-Werror -Wno-missing-field-initializers' gmake CC=cc ASAN= WSTACK= GCCFLAGS= example
